spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:mysql://localhost:3306/tasks?useSSL=false&serverTimezone=UTC
    username: root
    password: parkland_123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        cache:
          use_second_level_cache: true
          use_query_cache: true

logging:
  level:
    org:
      hibernate:
        cache=DEBUG:


management:
  endpoints:
    web:
      exposure:
        include: caches, cache
#  datasource:
#    driver_class_name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: sugarfactory
#    password: parkland_123
#
#  jpa:
#    database: ORACLE
#    database-platform: org.hibernate.dialect.OracleDialect
#    hibernate:
#      ddl-auto: none
#      #show-sql: true